postgres:
  persistence:
    size: 2Gi
managementServer:
  fullnameOverride: management-server-dev-2
  kargoTrace: "dev-0"
releases:
  postgresql:
    namespace: "vms-dev"
  managementServer:
    namespace: "vms-dev"
