postgres:
  persistence:
    size: 3Gi
managementServer:
  fullnameOverride: management-server-prod
  kargoTrace: "prod-0"
releases:
  postgresql:
    namespace: "vms-prod"
  managementServer:
    namespace: "vms-prod"
