postgres:
  persistence:
    size: 2Gi
managementServer:
  fullnameOverride: management-server-staging
  kargoTrace: "staging-0"
releases:
  postgresql:
    namespace: "vms-staging"
  managementServer:
    namespace: "vms-staging"
